### ISSUE TITLE
Operations fail when more than one iPhone connected to Mac

### ISSUE THREAD

**Issue by Gogle** [iOSForensics/pymobiledevice#8]
Most of the operations will fail when there are multiple iPhones connected to Mac.
This is because the initialisation of LockDownClient never takes the UDID as an argument.

**Comment by GotoHack** [comment]
Should be fixed by the following commits:
1ccc29ae981bca2afaebad351c5d36aaebd79394
24d2c89cc63b05b202eceea12c3ca5d7656278d3
f1ae36fc710d7653218be0a9f3b9a3d5eda2449f
f8cd23b18b2b7efea50ca33b92ca69d50cb7a411
d4c88b938be7722e6dd6feaaee2b1ffcf9e4729c
6817e0e82db36664d6758e46b8f1bb21886d23f2
0413bdb28ef0db0c456aa2ffa1e2035c9c0131d2
1c32480b69e9bb275de2f0b85031d7b89d4abd03
33fb7dd06fac7cb7b9334b82884a27f7c5e020ed
